'use client';
/* eslint-disable @next/next/no-img-element -- Scroll-composed raster layers use explicit intrinsic sizing and alpha. */
import { useCallback, useEffect, useRef, useState } from 'react';
import PhaseC from './phase-c';
import PhaseD from './phase-d';
import PhaseE from './phase-e';
import PhaseF from './phase-f';
import PhaseG from './phase-g';
import PersistentExploreChrome from './persistent-explore-chrome';
import { chapterForProgress, type ExploreChapter, type ExplorePhase } from './experience-map';
import { phaseCBeats, phaseDBeats, phaseEBeats, phaseFBeats, phaseGBeats } from './content';
import { withBasePath } from './base-path';
const clamp=(v:number,min=0,max=1)=>Math.min(max,Math.max(min,v));
const range=(p:number,s:number,e:number)=>clamp((p-s)/(e-s));
const windowed=(p:number,s:number,e:number,fade=.025)=>range(p,s,s+fade)*(1-range(p,e-fade,e));
const VOLUME_KEY='aussiecare-volume-v1';
const EXPLORE_RETURN_KEY='aussiecare-explore-return-v1';
const EXPLORE_PROGRESS_KEY='aussiecare-explore-progress-v1';
const LEGACY_VOLUME_KEY='undulatus-volume-v1';
const LEGACY_RETURN_KEY='undulatus-explore-return-v1';
const LEGACY_PROGRESS_KEY='undulatus-explore-progress-v1';
const PHASE_BEATS={c:phaseCBeats,d:phaseDBeats,e:phaseEBeats,f:phaseFBeats,g:phaseGBeats} as const;
type PhaseKey=keyof typeof PHASE_BEATS;
type ExploreProgress={scrollY:number;normalized:number;phase:'intro'|PhaseKey;beatId:string;label:string;savedAt:number};
type AudioEngine={ctx:AudioContext;master:GainNode;wind:GainNode;grass:GainNode;birds:GainNode;flock:GainNode;room:GainNode;outside:GainNode;water:GainNode;feather:GainNode;trust:GainNode;budgie:GainNode;budgieBuffer:AudioBuffer|null;budgieSource:AudioBufferSourceNode|null};
const PHASE_KEYS=Object.keys(PHASE_BEATS) as PhaseKey[];
function playBudgieCue(audio:AudioEngine,level=.055,duration=1.05){const buffer=audio.budgieBuffer;if(!buffer)return;const now=audio.ctx.currentTime;const source=audio.ctx.createBufferSource();const gain=audio.ctx.createGain();source.buffer=buffer;const usable=Math.max(0,buffer.duration-duration);const offset=usable?Math.random()*usable:0;gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(level,now+.025);gain.gain.exponentialRampToValueAtTime(.0001,now+duration);source.connect(gain).connect(audio.master);source.start(now,offset,Math.min(duration,buffer.duration-offset));source.stop(now+duration+.03)}
function currentExploreProgress():ExploreProgress{const maxScroll=Math.max(1,document.documentElement.scrollHeight-innerHeight);for(const phase of PHASE_KEYS){const node=document.querySelector<HTMLElement>(`#phase-${phase}`);if(!node)continue;const rect=node.getBoundingClientRect();if(rect.top<=innerHeight*.5&&rect.bottom>=innerHeight*.5){const phaseProgress=clamp(-rect.top/Math.max(1,node.offsetHeight-innerHeight));let beat=PHASE_BEATS[phase][0];for(const item of PHASE_BEATS[phase]){if(phaseProgress>=item.at)beat=item;else break}return{scrollY,normalized:clamp(scrollY/maxScroll),phase,beatId:beat.id,label:beat.title,savedAt:Date.now()}}}return{scrollY,normalized:clamp(scrollY/maxScroll),phase:'intro',beatId:'intro',label:'Australia',savedAt:Date.now()}}
function saveExploreProgress(){try{localStorage.setItem(EXPLORE_PROGRESS_KEY,JSON.stringify(currentExploreProgress()))}catch{/* The film remains usable when storage is unavailable. */}}
export default function Home(){
 const experienceRef=useRef<HTMLDivElement>(null); const phaseCProgressRef=useRef(0); const phaseDProgressRef=useRef(0); const phaseEProgressRef=useRef(0); const phaseFProgressRef=useRef(0); const phaseGProgressRef=useRef(0); const phaseEStateRef=useRef<'before'|'active'|'after'>('before'); const phaseFStateRef=useRef<'before'|'active'|'after'>('before'); const phaseGStateRef=useRef<'before'|'active'|'after'>('before'); const audioRef=useRef<AudioEngine|null>(null); const programmaticJumpRef=useRef(false); const [progress,setProgress]=useState(0); const [soundOn,setSoundOn]=useState(false); const [volume,setVolume]=useState(.65); const [menuOpen,setMenuOpen]=useState(false); const [activeChapter,setActiveChapter]=useState(0); const [jumping,setJumping]=useState(false);
 const dawn=.82+range(progress,0,.12)*.18,flock=range(progress,.12,.3),hero=range(progress,.25,.48),anatomy=range(progress,.46,.8),home=range(progress,.8,1),titleVisible=1-range(progress,.14,.23); const anatomyScene=range(anatomy,.08,.25),homeScene=range(home,.05,.22); const traits=['SOCIAL','CURIOSO','ACTIVO','INTELIGENTE']; const traitIndex=Math.min(3,Math.floor(range(progress,.745,.795)*4));
 const parts=[{name:'PICO',copy:'Come, explora y manipula.',x:31,y:14.5,side:'gutter'},{name:'CERA',copy:'Una zona clave para observar.',x:30,y:11.5,side:'gutter'},{name:'PLUMAJE',copy:'Protege y comunica su estado.',x:43,y:32,side:'gutter'},{name:'ALAS',copy:'Diseñadas para volar.',x:66,y:31,side:'gutter'},{name:'PATAS',copy:'Dos dedos delante y dos detrás.',x:42,y:56,side:'gutter'}] as const; const partIndex=Math.min(4,Math.floor(range(progress,.54,.78)*5)); const part=parts[partIndex];
 const beats=[{at:.1,kicker:'ORIGEN',title:'Australia'},{at:.27,kicker:'ENCUENTRO',title:'La bandada'},{at:.43,kicker:'PROTAGONISTA',title:'Jett'},{at:.51,kicker:'01 · CONÓCEME',title:'Aprende a observarme'},{at:.565,kicker:'ANATOMÍA',title:'Pico'},{at:.612,kicker:'IDENTIFICACIÓN',title:'Cera'},{at:.66,kicker:'COBERTURA',title:'Plumaje'},{at:.708,kicker:'MOVIMIENTO',title:'Alas'},{at:.756,kicker:'APOYO',title:'Patas'},{at:.88,kicker:'02 · MI HOGAR',title:'Un espacio seguro'}]; const beatIndex=progress<.18?0:progress<.35?1:progress<.49?2:progress<.54?3:progress<.8?4+partIndex:9; const beat=beats[beatIndex]; const reading=progress>.065&&progress<.18||progress>.49&&progress<.8||progress>.82;
 useEffect(()=>{let frame=0; const update=()=>{frame=0;const n=experienceRef.current;if(!n)return;const r=n.getBoundingClientRect();const next=clamp(-r.top/(n.offsetHeight-innerHeight));setProgress(next);if(r.bottom>0)setActiveChapter(chapterForProgress('intro',next));};const onScroll=()=>{if(!frame)frame=requestAnimationFrame(update)};update();addEventListener('scroll',onScroll,{passive:true});addEventListener('resize',onScroll);return()=>{removeEventListener('scroll',onScroll);removeEventListener('resize',onScroll);if(frame)cancelAnimationFrame(frame)}},[]);
 useEffect(()=>{let cancelled=false;const restore=async()=>{await document.fonts.ready;await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));if(cancelled)return;const params=new URLSearchParams(location.search);if(params.get('retorno')==='1'){try{const raw=sessionStorage.getItem(EXPLORE_RETURN_KEY)??sessionStorage.getItem(LEGACY_RETURN_KEY);if(raw){const saved=JSON.parse(raw) as {scrollY?:number};if(Number.isFinite(saved.scrollY))scrollTo({top:saved.scrollY,behavior:'instant'})}}catch{/* Fall through to the durable progress point. */}history.replaceState({},'',location.pathname);return;}const phase=params.get('fase');if(phase&&PHASE_KEYS.includes(phase as PhaseKey)){const phaseKey=phase as PhaseKey;const target=document.querySelector<HTMLElement>(`#phase-${phaseKey}`);if(!target)return;const beatId=params.get('beat');const beatIndex=beatId?PHASE_BEATS[phaseKey].findIndex(item=>item.id===beatId):-1;const beat=beatIndex>=0?PHASE_BEATS[phaseKey][beatIndex]:undefined;const nextBeat=beatIndex>=0?PHASE_BEATS[phaseKey][beatIndex+1]:undefined;const progressAt=beat?beat.at+(nextBeat?nextBeat.at-beat.at:.035)*.22:0;scrollTo({top:target.offsetTop+progressAt*Math.max(0,target.offsetHeight-innerHeight),behavior:'instant'});return}scrollTo({top:0,behavior:'instant'});};restore();return()=>{cancelled=true}},[]);
 useEffect(()=>{let timer=0;const persist=()=>{timer=0;saveExploreProgress()};const onScroll=()=>{if(!timer)timer=window.setTimeout(persist,650)};const onPageHide=()=>saveExploreProgress();addEventListener('scroll',onScroll,{passive:true});addEventListener('pagehide',onPageHide);return()=>{removeEventListener('scroll',onScroll);removeEventListener('pagehide',onPageHide);if(timer)clearTimeout(timer);saveExploreProgress()}},[]);
 useEffect(()=>{const raw=typeof localStorage==='undefined'?null:localStorage.getItem(VOLUME_KEY)??localStorage.getItem(LEGACY_VOLUME_KEY);const saved=raw===null?NaN:Number(raw);const frame=requestAnimationFrame(()=>{if(Number.isFinite(saved)&&saved>=0&&saved<=1)setVolume(saved)});return()=>cancelAnimationFrame(frame)},[]);
 useEffect(()=>{try{localStorage.setItem(VOLUME_KEY,String(volume))}catch{/* Keep audio usable without storage. */}const a=audioRef.current;if(a)a.master.gain.setTargetAtTime(volume,a.ctx.currentTime,.08)},[volume]);
 useEffect(()=>{
  const a=audioRef.current;if(!a)return;
  const t=a.ctx.currentTime;
  const phaseCProgress=phaseCProgressRef.current,phaseDProgress=phaseDProgressRef.current,phaseEProgress=phaseEProgressRef.current,phaseFProgress=phaseFProgressRef.current,phaseGProgress=phaseGProgressRef.current;
  const phaseEActive=phaseEStateRef.current==='active',phaseFActive=phaseFStateRef.current==='active',phaseGActive=phaseGStateRef.current==='active';
  const phaseGPresent=phaseGStateRef.current!=='before';
  const laterPhaseActive=phaseEStateRef.current==='after'||phaseFStateRef.current!=='before'||phaseGPresent;
  const phaseGAustralia=phaseGStateRef.current==='after'?1:phaseGActive?range(phaseGProgress,.825,.895):0;
  const australiaMix=laterPhaseActive?phaseGAustralia:1-homeScene;
  const earlyRoomMix=laterPhaseActive?0:homeScene*(1-phaseCProgress*.18);
  const waterMix=laterPhaseActive?0:range(phaseDProgress,.76,.88)*(1-range(phaseDProgress,.95,1));
  const healthMix=phaseEActive?1-range(phaseEProgress,.585,.62):0;
  const trustMix=phaseEActive?range(phaseEProgress,.575,.65)*(1-range(phaseEProgress,.94,1)):0;
  const phaseFNight=range(phaseFProgress,.885,.95);
  const phaseFRoom=phaseFActive?1-phaseFNight*.68:0;
  const phaseFOutside=phaseFActive?(1-phaseFNight)*(.42+range(phaseFProgress,.685,.735)*.48):0;
  const phaseFFlight=phaseFActive?range(phaseFProgress,.555,.62)*(1-range(phaseFProgress,.615,.635)):0;
  const phaseGRoom=phaseGActive?1-range(phaseGProgress,.03,.14):0;
  const phaseGFeather=phaseGActive?1-range(phaseGProgress,.79,.85):0;
  const phaseGWing=phaseGActive?range(phaseGProgress,.79,.83)*(1-range(phaseGProgress,.855,.875)):0;
  const introBudgie=windowed(progress,.25,.49,.045)*australiaMix;
  const finaleBudgie=phaseGStateRef.current==='after'?1:phaseGActive?range(phaseGProgress,.84,.9):0;
  a.wind.gain.setTargetAtTime(soundOn?((.026-dawn*.009)*australiaMix):0,t,.25);
  a.grass.gain.setTargetAtTime(soundOn?((.006+dawn*.009)*australiaMix):0,t,.24);
  a.birds.gain.setTargetAtTime(soundOn?((.001+flock*.01)*australiaMix):0,t,.18);
  a.flock.gain.setTargetAtTime(soundOn?((hero*.013+.002)*australiaMix):0,t,.14);
  a.room.gain.setTargetAtTime(soundOn?(.008*earlyRoomMix+.008*phaseFRoom+.004*phaseGRoom):0,t,.26);
  a.outside.gain.setTargetAtTime(soundOn?((.002+phaseCProgress*.003)*earlyRoomMix+.004*phaseFOutside+.0015*phaseGRoom):0,t,.26);
  a.water.gain.setTargetAtTime(soundOn?.012*waterMix:0,t,.18);
  a.feather.gain.setTargetAtTime(soundOn?(.003*healthMix+.002*phaseFNight+.003*phaseGFeather):0,t,.2);
  a.trust.gain.setTargetAtTime(soundOn?(.003*trustMix+.009*phaseFFlight+.009*phaseGWing):0,t,.2);
  a.budgie.gain.setTargetAtTime(soundOn?(.04*introBudgie+.06*finaleBudgie):0,t,.2);
 },[soundOn,dawn,flock,hero,homeScene,progress]);
 useEffect(()=>{if(!menuOpen)return;document.body.classList.add('aussiecare-menu-open');const close=(event:KeyboardEvent)=>{if(event.key==='Escape')setMenuOpen(false)};addEventListener('keydown',close);return()=>{document.body.classList.remove('aussiecare-menu-open');removeEventListener('keydown',close)}},[menuOpen]);
 const handleVolumeChange=useCallback((next:number)=>setVolume(clamp(next)),[]);
 const toggleSound=useCallback(()=>{if(!audioRef.current){const ctx=new AudioContext();const master=ctx.createGain();master.gain.value=volume;master.connect(ctx.destination);const noiseBuffer=ctx.createBuffer(1,ctx.sampleRate*3,ctx.sampleRate);const data=noiseBuffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=Math.random()*2-1;const makeNoise=(frequency:number)=>{const source=ctx.createBufferSource();source.buffer=noiseBuffer;source.loop=true;const filter=ctx.createBiquadFilter();filter.type='bandpass';filter.frequency.value=frequency;filter.Q.value=.45;const gain=ctx.createGain();gain.gain.value=0;source.connect(filter).connect(gain).connect(master);source.start(0,Math.random()*noiseBuffer.duration);return gain};const wind=makeNoise(420),grass=makeNoise(2600),birds=makeNoise(5100),flock=makeNoise(7300),room=makeNoise(170),outside=makeNoise(1900),water=makeNoise(3400),feather=makeNoise(760),trust=makeNoise(2300);const budgie=ctx.createGain();budgie.gain.value=0;budgie.connect(master);const engine:AudioEngine={ctx,master,wind,grass,birds,flock,room,outside,water,feather,trust,budgie,budgieBuffer:null,budgieSource:null};audioRef.current=engine;void fetch(withBasePath('/audio/budgerigar-chirping-public-domain.ogg')).then(response=>{if(!response.ok)throw new Error('audio');return response.arrayBuffer()}).then(data=>ctx.decodeAudioData(data)).then(buffer=>{if(audioRef.current!==engine)return;engine.budgieBuffer=buffer;const source=ctx.createBufferSource();source.buffer=buffer;source.loop=true;source.connect(budgie);source.start(0,Math.random()*buffer.duration);engine.budgieSource=source}).catch(()=>{/* El paisaje sintético sigue disponible si falla la grabación. */})}const audio=audioRef.current;if(soundOn)audio.ctx.suspend();else audio.ctx.resume();setSoundOn(v=>!v)},[soundOn,volume]);
 useEffect(()=>{const onVisibility=()=>{const audio=audioRef.current;if(!audio)return;if(document.hidden)audio.ctx.suspend();else if(soundOn)audio.ctx.resume()};document.addEventListener('visibilitychange',onVisibility);return()=>document.removeEventListener('visibilitychange',onVisibility)},[soundOn]);
 const handlePhaseCProgress=(next:number)=>{phaseCProgressRef.current=next;setActiveChapter(chapterForProgress('c',next));const audio=audioRef.current;if(!audio)return;const now=audio.ctx.currentTime;const roomMix=homeScene*(1-next*.18);audio.room.gain.setTargetAtTime(soundOn ? .014*roomMix : 0,now,.12);audio.outside.gain.setTargetAtTime(soundOn ? (.004+next*.006)*roomMix : 0,now,.12);audio.budgie.gain.setTargetAtTime(soundOn?.016*windowed(next,.5,.61):0,now,.16)};
 const handlePhaseDProgress=useCallback((next:number)=>{phaseDProgressRef.current=next;setActiveChapter(chapterForProgress('d',next));const audio=audioRef.current;if(!audio)return;const now=audio.ctx.currentTime;const waterMix=range(next,.76,.88)*(1-range(next,.95,1));audio.room.gain.setTargetAtTime(soundOn ? .011 : 0,now,.16);audio.outside.gain.setTargetAtTime(soundOn ? .003 : 0,now,.16);audio.water.gain.setTargetAtTime(soundOn ? .018*waterMix : 0,now,.12);audio.budgie.gain.setTargetAtTime(soundOn?.017*range(next,.955,.98):0,now,.16)},[soundOn]);
 const handlePhaseEProgress=useCallback((next:number)=>{phaseEProgressRef.current=next;setActiveChapter(chapterForProgress('e',next));const audio=audioRef.current;if(!audio)return;const now=audio.ctx.currentTime;const healthMix=1-range(next,.585,.62);const trustMix=range(next,.575,.65)*(1-range(next,.94,1));const flightMix=range(next,.94,1);audio.water.gain.setTargetAtTime(0,now,.12);audio.room.gain.setTargetAtTime(soundOn ? .006 : 0,now,.18);audio.outside.gain.setTargetAtTime(soundOn ? .0015+flightMix*.004 : 0,now,.16);audio.feather.gain.setTargetAtTime(soundOn ? .003*healthMix : 0,now,.14);audio.trust.gain.setTargetAtTime(soundOn ? .003*trustMix+.009*flightMix : 0,now,.12);audio.budgie.gain.setTargetAtTime(soundOn?.025*flightMix:0,now,.16)},[soundOn]);
 const handlePhaseESceneState=useCallback((state:'before'|'active'|'after')=>{phaseEStateRef.current=state;const audio=audioRef.current;if(!audio||state==='active')return;const now=audio.ctx.currentTime;audio.feather.gain.setTargetAtTime(0,now,.14);audio.trust.gain.setTargetAtTime(0,now,.14);audio.budgie.gain.setTargetAtTime(0,now,.14);if(state==='after'){audio.water.gain.setTargetAtTime(0,now,.14);audio.room.gain.setTargetAtTime(0,now,.22);audio.outside.gain.setTargetAtTime(0,now,.22)}},[]);
 const handlePhaseFProgress=useCallback((next:number)=>{phaseFProgressRef.current=next;setActiveChapter(chapterForProgress('f',next));const audio=audioRef.current;if(!audio)return;const now=audio.ctx.currentTime;const nightMix=range(next,.885,.95)*(1-range(next,.965,1));const roomMix=1-nightMix*.68;const outsideMix=(1-nightMix)*(.42+range(next,.685,.735)*.48);const flightMix=range(next,.555,.62)*(1-range(next,.615,.635));audio.water.gain.setTargetAtTime(0,now,.12);audio.room.gain.setTargetAtTime(soundOn?.008*roomMix:0,now,.2);audio.outside.gain.setTargetAtTime(soundOn?.004*outsideMix:0,now,.2);audio.feather.gain.setTargetAtTime(soundOn?.002*nightMix:0,now,.2);audio.trust.gain.setTargetAtTime(soundOn?.009*flightMix:0,now,.12);audio.budgie.gain.setTargetAtTime(soundOn?.032*flightMix:0,now,.14)},[soundOn]);
 const handlePhaseFSceneState=useCallback((state:'before'|'active'|'after')=>{phaseFStateRef.current=state;const audio=audioRef.current;if(!audio||state==='active')return;const now=audio.ctx.currentTime;audio.room.gain.setTargetAtTime(0,now,.22);audio.outside.gain.setTargetAtTime(0,now,.22);audio.feather.gain.setTargetAtTime(0,now,.18);audio.trust.gain.setTargetAtTime(0,now,.14);audio.budgie.gain.setTargetAtTime(0,now,.14)},[]);
 const handlePhaseGProgress=useCallback((next:number)=>{phaseGProgressRef.current=next;setActiveChapter(chapterForProgress('g',next));const audio=audioRef.current;if(!audio)return;const now=audio.ctx.currentTime;const returnMix=range(next,.825,.895);const roomMix=1-range(next,.03,.14);const constellationMix=1-range(next,.79,.85);const wingMix=range(next,.79,.83)*(1-range(next,.855,.875));const singingMix=windowed(next,.17,.255,.03);const finaleSong=range(next,.84,.9);audio.water.gain.setTargetAtTime(0,now,.12);audio.room.gain.setTargetAtTime(soundOn?.004*roomMix:0,now,.2);audio.outside.gain.setTargetAtTime(soundOn?.0015*roomMix:0,now,.2);audio.feather.gain.setTargetAtTime(soundOn?.003*constellationMix:0,now,.18);audio.trust.gain.setTargetAtTime(soundOn?.009*wingMix:0,now,.12);audio.wind.gain.setTargetAtTime(soundOn?.024*returnMix:0,now,.22);audio.grass.gain.setTargetAtTime(soundOn?.011*returnMix:0,now,.22);audio.birds.gain.setTargetAtTime(soundOn?.008*range(next,.85,.93):0,now,.16);audio.flock.gain.setTargetAtTime(soundOn?.008*range(next,.87,.95):0,now,.12);audio.budgie.gain.setTargetAtTime(soundOn?singingMix*.05+finaleSong*.045:0,now,.18)},[soundOn]);
 const handlePhaseGSceneState=useCallback((state:'before'|'active'|'after')=>{phaseGStateRef.current=state;const audio=audioRef.current;if(!audio||state==='active')return;const now=audio.ctx.currentTime;if(state==='before'){audio.wind.gain.setTargetAtTime(0,now,.18);audio.grass.gain.setTargetAtTime(0,now,.18);audio.birds.gain.setTargetAtTime(0,now,.14);audio.flock.gain.setTargetAtTime(0,now,.14);audio.budgie.gain.setTargetAtTime(0,now,.16)}else{audio.wind.gain.setTargetAtTime(soundOn?.024:0,now,.2);audio.grass.gain.setTargetAtTime(soundOn?.011:0,now,.2);audio.birds.gain.setTargetAtTime(soundOn?.008:0,now,.16);audio.flock.gain.setTargetAtTime(soundOn?.008:0,now,.14);audio.budgie.gain.setTargetAtTime(soundOn?.06:0,now,.2)}audio.room.gain.setTargetAtTime(0,now,.18);audio.outside.gain.setTargetAtTime(0,now,.18);audio.feather.gain.setTargetAtTime(0,now,.16);audio.trust.gain.setTargetAtTime(0,now,.14)},[soundOn]);
 const playFoley=useCallback((beatIndex:number)=>{const audio=audioRef.current;if(!soundOn||!audio||beatIndex===0)return;if(beatIndex===8)playBudgieCue(audio,.052,1.05);const now=audio.ctx.currentTime;const oscillator=audio.ctx.createOscillator();const gain=audio.ctx.createGain();const cageBeat=beatIndex>=2&&beatIndex<=8;oscillator.type=cageBeat?'triangle':'sine';oscillator.frequency.setValueAtTime(cageBeat?240+beatIndex*24:420+beatIndex*18,now);oscillator.frequency.exponentialRampToValueAtTime(cageBeat?150:280,now+.11);gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(cageBeat ? .018 : .012,now+.012);gain.gain.exponentialRampToValueAtTime(.0001,now+.15);oscillator.connect(gain).connect(audio.master);oscillator.start(now);oscillator.stop(now+.17)},[soundOn]);
 const playPhaseDFoley=useCallback((beatIndex:number)=>{const audio=audioRef.current;if(!soundOn||!audio||beatIndex===0)return;if(beatIndex===16)playBudgieCue(audio,.05,1.05);const now=audio.ctx.currentTime;const oscillator=audio.ctx.createOscillator();const gain=audio.ctx.createGain();const warningBeat=beatIndex>=9&&beatIndex<=11;const cleaningBeat=beatIndex>=13;oscillator.type=cleaningBeat?'triangle':'sine';const start=warningBeat?178:cleaningBeat?520:330+beatIndex*17;oscillator.frequency.setValueAtTime(start,now);oscillator.frequency.exponentialRampToValueAtTime(warningBeat?112:cleaningBeat?240:210,now+.13);gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(warningBeat?.009:.013,now+.012);gain.gain.exponentialRampToValueAtTime(.0001,now+.17);oscillator.connect(gain).connect(audio.master);oscillator.start(now);oscillator.stop(now+.19)},[soundOn]);
 const playPhaseEFoley=useCallback((beatIndex:number)=>{const audio=audioRef.current;if(!soundOn||!audio||beatIndex===0)return;if(beatIndex===1||beatIndex===11||beatIndex===16||beatIndex===19)playBudgieCue(audio,beatIndex===19?.065:.048,1.1);const now=audio.ctx.currentTime;const oscillator=audio.ctx.createOscillator();const gain=audio.ctx.createGain();const actBeat=beatIndex>=8&&beatIndex<=10;const trustBeat=beatIndex>=11;const stepBeat=beatIndex===16||beatIndex===17;oscillator.type=actBeat?'triangle':'sine';const start=actBeat?172:stepBeat?620:trustBeat?410:285+beatIndex*13;oscillator.frequency.setValueAtTime(start,now);oscillator.frequency.exponentialRampToValueAtTime(actBeat?104:stepBeat?360:220,now+.14);gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(actBeat?.009:stepBeat?.014:.011,now+.012);gain.gain.exponentialRampToValueAtTime(.0001,now+.18);oscillator.connect(gain).connect(audio.master);oscillator.start(now);oscillator.stop(now+.2)},[soundOn]);
 const playPhaseFFoley=useCallback((beatIndex:number)=>{const audio=audioRef.current;if(!soundOn||!audio||beatIndex===0)return;if(beatIndex===12||beatIndex===13)playBudgieCue(audio,.052,1.08);const now=audio.ctx.currentTime;const oscillator=audio.ctx.createOscillator();const gain=audio.ctx.createGain();const hazardBeat=beatIndex>=3&&beatIndex<=11;const safeBeat=beatIndex===12||beatIndex===13;const nightBeat=beatIndex>=19;oscillator.type=hazardBeat?'triangle':'sine';const start=hazardBeat?230+beatIndex*9:safeBeat?590:nightBeat?260:390;oscillator.frequency.setValueAtTime(start,now);oscillator.frequency.exponentialRampToValueAtTime(hazardBeat?145:safeBeat?330:nightBeat?180:245,now+.14);gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(hazardBeat?.009:safeBeat?.014:nightBeat?.006:.01,now+.012);gain.gain.exponentialRampToValueAtTime(.0001,now+.18);oscillator.connect(gain).connect(audio.master);oscillator.start(now);oscillator.stop(now+.2)},[soundOn]);
 const playPhaseGFoley=useCallback((beatIndex:number)=>{const audio=audioRef.current;if(!soundOn||!audio||beatIndex===0)return;if(beatIndex===3||beatIndex===15)playBudgieCue(audio,beatIndex===3?.072:.056,beatIndex===3?1.35:1.05);const now=audio.ctx.currentTime;const oscillator=audio.ctx.createOscillator();const gain=audio.ctx.createGain();const vocalBeat=beatIndex===3;const wingBeat=beatIndex===15||beatIndex===16;oscillator.type=vocalBeat?'sine':wingBeat?'triangle':'sine';const start=vocalBeat?1180:wingBeat?360:270+beatIndex*11;oscillator.frequency.setValueAtTime(start,now);oscillator.frequency.exponentialRampToValueAtTime(vocalBeat?760:wingBeat?135:205,now+(vocalBeat?.18:.14));gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(vocalBeat?.008:wingBeat?.013:.006,now+.012);gain.gain.exponentialRampToValueAtTime(.0001,now+(vocalBeat?.23:.18));oscillator.connect(gain).connect(audio.master);oscillator.start(now);oscillator.stop(now+(vocalBeat?.25:.2))},[soundOn]);
 const jumpWithinFilm=useCallback((phase:ExplorePhase,targetProgress:number,chapter:number,beatId:string)=>{setMenuOpen(false);setJumping(true);programmaticJumpRef.current=true;window.setTimeout(()=>{const target=phase==='intro'?experienceRef.current:document.querySelector<HTMLElement>(`#phase-${phase}`);if(!target){setJumping(false);programmaticJumpRef.current=false;return}const top=phase==='intro'?target.offsetTop+targetProgress*Math.max(0,target.offsetHeight-innerHeight):target.offsetTop+targetProgress*Math.max(0,target.offsetHeight-innerHeight);history.replaceState({},'',phase==='intro'?location.pathname:`${location.pathname}?fase=${phase}&beat=${encodeURIComponent(beatId)}`);scrollTo({top,behavior:'instant'});setActiveChapter(chapter);requestAnimationFrame(()=>requestAnimationFrame(()=>{setJumping(false);window.setTimeout(()=>{programmaticJumpRef.current=false},180);document.querySelector<HTMLElement>(phase==='intro'?'.intro-copy h1':`#phase-${phase} h2`)?.focus({preventScroll:true})}))},130)},[]);
 const restartExperience=useCallback(()=>{try{localStorage.removeItem(EXPLORE_PROGRESS_KEY);localStorage.removeItem(LEGACY_PROGRESS_KEY);sessionStorage.removeItem(EXPLORE_RETURN_KEY);sessionStorage.removeItem(LEGACY_RETURN_KEY)}catch{/* Storage is optional. */}jumpWithinFilm('intro',0,0,'origin')},[jumpWithinFilm]);
 const jumpToChapter=useCallback((chapter:ExploreChapter)=>jumpWithinFilm(chapter.phase,chapter.progress,chapter.number,chapter.beatId),[jumpWithinFilm]);
 const openConsult=useCallback(()=>{setMenuOpen(false);const snapshot=currentExploreProgress();saveExploreProgress();try{sessionStorage.setItem(EXPLORE_RETURN_KEY,JSON.stringify({...snapshot,soundOn,volume}))}catch{/* The durable local point still remains when session storage is blocked. */}audioRef.current?.ctx.suspend();location.assign(withBasePath('/consulta/'))},[soundOn,volume]);
 return <main><PersistentExploreChrome activeChapter={activeChapter} menuOpen={menuOpen} soundOn={soundOn} volume={volume} onHome={restartExperience} onOpenConsult={openConsult} onSelectChapter={jumpToChapter} onToggleMenu={()=>setMenuOpen(current=>!current)} onCloseMenu={()=>setMenuOpen(false)} onToggleSound={toggleSound} onVolumeChange={handleVolumeChange}/><div className="aussiecare-jump-curtain" data-visible={jumping?'true':'false'} aria-hidden="true"/><p className="sr-only" role="status" aria-live="polite">{activeChapter?`Capítulo ${activeChapter}`:'Origen, Australia'}</p><div className="experience" id="phase-intro" ref={experienceRef}><div className="stage" inert={progress >= .999} aria-hidden={progress >= .999}>
  <section className="australia" style={{opacity:1-range(anatomy,0,.2)}} aria-label="Australia al amanecer"><img className="australia-image" src={withBasePath('/assets/australia-master.webp')} alt="Pastizal australiano al amanecer" fetchPriority="high" decoding="async" style={{transform:`scale(${1.08+progress*.18}) translateY(${progress*-3}%)`,filter:`brightness(${.25+dawn*.75}) saturate(${.65+dawn*.35})`}}/><div className="sky-wash" style={{opacity:1-dawn}}/><div className="grass-layer grass-back" style={{transform:`translate3d(0,${progress*7}%,0)`}}/><div className="grass-layer grass-front" style={{transform:`translate3d(${progress*-2}%,${progress*13}%,0) scale(1.08)`}}/><div className="flock" style={{opacity:flock*(1-hero),transform:`translate3d(${flock*22-12}vw,${18-flock*12}vh,0) scale(${.35+flock*1.1})`}} aria-hidden="true">{Array.from({length:11},(_,i)=><img key={i} src={withBasePath('/assets/bud-hero-flight-v2.webp')} alt="" loading="eager" decoding="async" style={{'--i':i} as React.CSSProperties}/>)}</div></section>
  <section className="intro-copy" style={{opacity:titleVisible*dawn}}><p className="eyebrow">Origen · Prólogo</p><h1 tabIndex={-1}>AUSTRALIA</h1><p>El hogar natural del periquito australiano.</p></section>
  <section className="hero-flight" style={{opacity:hero*(1-range(anatomy,0,.16)),transform:`translate3d(calc(-50% + ${(1-hero)*45}vw),${18-hero*12}vh,0) scale(${.18+hero*.68}) rotate(${8-hero*12}deg)`}}><div className="bird-crop" role="img" aria-label="Jett, el periquito protagonista" style={{backgroundImage:`url(${withBasePath('/assets/bud-hero-flight-v2.webp')})`}}/></section>
  <section className="anatomy" style={{opacity:anatomyScene*(1-homeScene)}}><div className="paper" style={{transform:`scale(${1.1-anatomy*.1})`}}><div className="anatomy-figure"><img src={withBasePath('/assets/bud-hero-perched-v3.webp')} alt="Jett posado para reconocer su anatomía" loading="lazy" decoding="async"/>{progress>=.54&&<div className={`part-callout ${part.side} part-${part.name.toLowerCase()}`} key={part.name} style={{'--pin-x':`${part.x}%`,'--pin-y':`${part.y}%`} as React.CSSProperties}><i/><span><b>{part.name}</b><small>{part.copy}</small></span></div>}</div><div className="chapter-number">01</div><div className="chapter-copy"><p className="eyebrow dark">Antes de cuidarme</p><h2>CONÓCEME</h2><p>Aprende a observarme.</p></div><div className="measure" style={{opacity:1-range(progress,.56,.61)}}><span>≈ 18 cm</span></div><div className="trait" key={traitIndex} style={{opacity:range(progress,.745,.775)}}>{traits[traitIndex]}</div></div></section>
  <section className="home" style={{opacity:homeScene}}><img src={withBasePath('/assets/room-base-empty-v3.webp')} alt="ROOM-BASE modular, preparado para recibir el hogar del periquito" loading="lazy" decoding="async" style={{transform:`scale(${1.14-home*.08}) translateX(${(1-home)*4}%)`}}/><div className="home-grade"/><div className="home-copy" style={{opacity:range(home,.45,.8),transform:`translateY(${(1-home)*24}px)`}}><p className="eyebrow">02 · Entrada</p><h2>MI HOGAR</h2><p>Un único espacio. Muchos estados.</p></div></section>
  {progress>=.035&&<div className="beat-card" data-reading={reading} key={beat.title}><span>{beat.kicker}</span><strong>{beat.title}</strong><small>{reading?'Lee a tu ritmo · continúa cuando estés listo':'Sigue deslizando para avanzar'}</small><i><b/></i></div>}
  <div className="progress-rail" aria-label={`Momento ${beatIndex+1} de ${beats.length}: ${beat.title}`}><i className="progress-fill" style={{height:`${progress*100}%`}}/>{beats.map((item,index)=><span key={item.title} className={index===beatIndex?'active':''} style={{top:`${item.at*100}%`}}><b>{String(index+1).padStart(2,'0')}</b></span>)}</div>{progress<.05&&<div className="scroll-cue"><span>Desliza para entrar</span><b>↓</b></div>}
 </div></div>
 <PhaseC onProgress={handlePhaseCProgress} onBeatChange={(index)=>{if(!programmaticJumpRef.current)playFoley(index)}}/>
 <PhaseD onProgress={handlePhaseDProgress} onBeatChange={(index)=>{if(!programmaticJumpRef.current)playPhaseDFoley(index)}}/>
 <PhaseE onProgress={handlePhaseEProgress} onBeatChange={(index)=>{if(!programmaticJumpRef.current)playPhaseEFoley(index)}} onSceneState={handlePhaseESceneState}/>
 <PhaseF onProgress={handlePhaseFProgress} onBeatChange={(index)=>{if(!programmaticJumpRef.current)playPhaseFFoley(index)}} onSceneState={handlePhaseFSceneState}/>
 <PhaseG onProgress={handlePhaseGProgress} onBeatChange={(index)=>{if(!programmaticJumpRef.current)playPhaseGFoley(index)}} onSceneState={handlePhaseGSceneState} onRestart={restartExperience} onOpenConsult={openConsult}/>
 </main>;
}
